### ISSUE TITLE
new ReferenceError("st_index is not defined", "undefined", 1)

### ISSUE THREAD

**Issue by irishmark** [cloudant-labs/hastings#10]
Still struggling to get this working with couchDB
With either the tropperstyle fork or using trunk and the instruction I always end up with the above error when I run the hastings sample code:
new ReferenceError("st_index is not defined", "undefined", 1)
The test GET call returns a 200 but with no results, presumably cos the index isn't created but I'm at a loss as to why

I'm a bit stumped by this one, isn't that supposed to be a function built-in to couchDB?
Sorry, total n00b with this stuff but trying to learn fast..

**Comment by irishmark** [comment]
Is st_index Cloudant-only at the minute?

**Comment by jiangphcn** [comment]
Do you have chance to read the following wiki page?
 https://github.com/cloudant-labs/hastings/wiki/Introduce-GeoSpatial-Index-To-CouchDB

Although it is not up to date, it includes some necessary information to change.

**Comment by irishmark** [comment]
Yeah, been following that page, took me a few tries till I got it to build without errors. So now it looks like its working, but when I run the hastings sample (which I found in the hastings source - https://github.com/cloudant-labs/hastings/tree/master/sample) it creates the following doc:

designDoc = {"_id" : designDocId,
                        "st_indexes" : {indexName : {
                                "index" : "function(doc){\
                                                        if (doc.geometry) \
                                                        { \
                                                                st_index(doc.geometry);\
                                                        }\
                                                }"
                                        }
                                }
                        }

But if I then run the sample it says "st_index" doesn't exist. I've grepped the codebase of everything I installed as part of this and there is no st_index function anywhere as far as I can see, so I'm at a loss as to how this sample code is supposed to work. I tried changing it to "easton_index" or even "emit". Emit is at least a found function, but didn't seem to work. 
You'll have to excuse my lack of geo knowledge, I'm just a devOp setting this up for the devs.

**Comment by jiangphcn** [comment]
I just updated wiki and please perform `add sandbox.st_index = Spatial.index; to loop.js under share/server directory` mentioned in https://github.com/cloudant-labs/hastings/wiki/Introduce-GeoSpatial-Index-To-CouchDB#enable-spatialjs-for-hastings

**Comment by irishmark** [comment]
Nice one! works perfectly, thanks

**Comment by irishmark** [comment]
@jiangphcn I don't suppose you would consider making a new release? My company are nervous of investing time on a tech unless it's got a version number and it's been a while since the last one
