### ISSUE TITLE
How exactly should we change `src/hastings_index_updater.erl`?

### ISSUE THREAD

**Issue by Ravenstine** [cloudant-labs/hastings#11]
In the instructions for installing for CouchDB, it says that `src/hastings_index_updater.erl` should be modified.  The problems is that the Hastings code gets pulled in and run by the CouchDB build process... does this mean that we should fork Hastings in order for it to work with CouchDB?

**Comment by jiangphcn** [comment]
No, I don't think that you need to fork hastings to make it work. Because `cloudant_util:customer_name(Db)` is cloudant thing, you have to remove this line or change it to make hastings to work in couchdb codebase.

**Comment by kontrollanten** [comment]
One way is to have a sed cmd ran after `./configure`

```
  sed -i '/{user, cloudant_util:customer_name(Db)},/d' src/hastings/src/hastings_index_updater.erl
```
