### ISSUE TITLE
"payment_required" error while hitting Index

### ISSUE THREAD

**Issue by furrycoat21** [cloudant-labs/hastings#2]
While building CouchDB 2.0 with hastings/easton I didn't enable hastings in the .ini files
`[hastings]
enabled = true`

This resulted in the following error whenever I hit the Geospatial index. 
`{
"error": "unknown_error",
"reason": "payment_required"
}`

This seems to be a relic of cloudant that should be removed.

**Comment by tropperstyle** [comment]
I'm new to couchdb/erlang/beam. I would greatly appreciate if you could share each step to get this up and running. I asked about this in #1

**Comment by jiangphcn** [comment]
Please see updated wiki https://github.com/cloudant-labs/hastings/wiki/Introduce-GeoSpatial-Index-To-CouchDB
