### ISSUE TITLE
Error with sample files

### ISSUE THREAD

**Issue by irishmark** [cloudant-labs/hastings#9]
Been trying for a few days now to get this working with couchDB 2.1.0 but the sample files always fail like so, Any idea what I'm doing wrong?

$python loader.py
...
...
[notice] 2017-09-29T11:53:18.168921Z couchdb@localhost <0.2289.0> e15f38fda3 localhost:5984 127.0.0.1 undefined POST /countries 201 ok 7
[notice] 2017-09-29T11:53:18.175990Z couchdb@localhost <0.2296.0> b2f8b4c14b localhost:5984 127.0.0.1 undefined POST /countries 201 ok 7
[error] 2017-09-29T11:53:18.192793Z couchdb@localhost <0.2427.0> b8b2838275 rexi_server: from: couchdb@localhost(<0.2303.0>) mfa: hastings_rpc:search/4 error:undef [{couch_crypto,hash,[md5,<<131,104,4,109,0,0,0,94,102,117,110,99,116,105,111,110,40,100,111,99,41,123,9,9,9,9,9,9,9,105,102,32,40,100,111,99,46,103,101,111,109,101,116,114,121,41,32,9,9,9,9,9,9,9,123,32,9,9,9,9,9,9,9,9,115,116,95,105,110,100,101,120,40,100,111,99,46,103,101,111,109,101,116,114,121,41,59,9,9,9,9,9,9,9,125,9,9,9,9,9,9,125,109,0,0,0,5,114,116,114,101,101,97,2,98,0,0,16,230>>],[]},{hastings_index,set_index_sig,1,[{file,"src/hastings_index.erl"},{line,421}]},{hastings_index,design_doc_to_index_int,3,[{file,"src/hastings_index.erl"},{line,406}]},{hastings_index,design_doc_to_index,2,[{file,"src/hastings_index.erl"},{line,84}]},{hastings_rpc,get_index_pid,3,[{file,"src/hastings_rpc.erl"},{line,60}]},{hastings_rpc,search,4,[{file,"src/hastings_rpc.erl"},{line,22}]},{rexi_server,init_p,3,[{file,"src/rexi_server.erl"},{line,139}]}]
[notice] 2017-09-29T11:53:18.198294Z couchdb@localhost <0.2303.0> b8b2838275 localhost:5984 127.0.0.1 undefined GET /countries/_design/SpatialView/_geo/countries?bbox=0.000000,51.000000,0.000000,51.000000 500 ok 22

**Comment by jiangphcn** [comment]
try to change `couch_crypto:hash` to `crypto:hash`
